"""Self-seed golden YAML by transcribing audio fixtures against current baseline.

The golden text comes from whatever the baseline server.py produces. This is
a regression-test fixture, not absolute ground truth — see
wiki/patterns/engine-regression-test-self-seeded-reference.md.

Pre-req:
    1. fixtures/audio/*.wav populated (real utterances, not stubs)
    2. baseline server up at --server-url

Usage:
    # In one shell
    cd ../voice-input-mimo
    uvicorn server.server:app --host 127.0.0.1 --port 8765

    # In another shell, from worktree root
    python scripts/seed_golden.py
    # → fixtures/golden/transcripts.yaml is rewritten
"""

from __future__ import annotations

import argparse
import asyncio
import wave
from datetime import datetime, timezone
from pathlib import Path

import httpx
import yaml

from _baseline_meta import git_meta


def _probe_duration_s(wav_path: Path) -> float:
    with wave.open(str(wav_path), "rb") as w:
        return w.getnframes() / w.getframerate()


def _category(duration_s: float) -> str:
    if duration_s < 5:
        return "short"
    if duration_s < 10:
        return "medium"
    if duration_s < 20:
        return "long"
    return "extra-long"


async def _transcribe(client: httpx.AsyncClient, url: str, audio_path: Path, language: str) -> str:
    with audio_path.open("rb") as f:
        files = {"file": (audio_path.name, f, "audio/wav")}
        data = {"language": language}
        resp = await client.post(
            f"{url}/v1/audio/transcriptions", files=files, data=data, timeout=180.0
        )
        resp.raise_for_status()
    return resp.json().get("text", "")


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--server-url", default="http://127.0.0.1:8765")
    ap.add_argument("--audio-dir", type=Path, default=Path("fixtures/audio"))
    ap.add_argument("--out", type=Path, default=Path("fixtures/golden/transcripts.yaml"))
    ap.add_argument("--language", default="zh")
    ap.add_argument("--repo-path", type=Path, default=Path(__file__).resolve().parent.parent)
    args = ap.parse_args()

    if not args.audio_dir.exists():
        raise SystemExit(f"audio dir not found: {args.audio_dir}")
    wavs = sorted(args.audio_dir.glob("*.wav"))
    if not wavs:
        raise SystemExit(f"no wav under {args.audio_dir}")

    meta = git_meta(args.repo_path)
    seeded_at = datetime.now(timezone.utc).isoformat()

    items: dict[str, dict] = {}
    async with httpx.AsyncClient() as client:
        for wav in wavs:
            duration = _probe_duration_s(wav)
            try:
                text = await _transcribe(client, args.server_url, wav, args.language)
            except httpx.HTTPError as e:
                items[wav.name] = {"error": str(e), "skip": True}
                print(f"  {wav.name}: error → {e}")
                continue
            items[wav.name] = {
                "text": text,
                "lang": "zh-tw",
                "duration_s": round(duration, 2),
                "category": _category(duration),
                "source": "self-seeded against baseline",
                "seeded_at": seeded_at,
                "seeded_by_engine_sha": meta["git_sha"],
                "seeded_by_engine_clean": meta["git_status_clean"],
            }
            preview = text[:50] + ("…" if len(text) > 50 else "")
            print(f"  {wav.name} ({duration:.1f}s) → {preview}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Self-seeded golden transcripts.\n"
        "# Generated by scripts/seed_golden.py against baseline server.py.\n"
        f"# Seeded at:             {seeded_at}\n"
        f"# Seeded by engine sha:  {meta['git_sha']} (clean={meta['git_status_clean']})\n"
        "# Pattern reference:     wiki/patterns/engine-regression-test-self-seeded-reference.md\n"
        "# Re-run seed_golden.py to refresh.\n\n"
    )
    with args.out.open("w") as f:
        f.write(header)
        yaml.safe_dump(items, f, allow_unicode=True, sort_keys=False)
    print(f"wrote {args.out} ({len(items)} entries)")


if __name__ == "__main__":
    asyncio.run(main())
