import AppKit
import Carbon

/// Inject refined text via clipboard + Cmd+V.
///
/// UserDefaults toggles (no rebuild needed):
///   skipIMESwitch              Bool default false  → skip Chinese IME → ASCII switch (faster, but Cmd+V may be intercepted in IME-active apps)
///   skipClipboardRestore       Bool default true   → skip restoring previous clipboard (avoids 2nd Universal Clipboard sync = main-thread freeze)
///   markPasteboardTransient    Bool default true   → tag clipboard as transient (clipboard managers + best-effort skip Universal Clipboard sync)
///   clipboardArchiveEnabled    Bool default true   → save pre-paste clipboard to ~/Library/Application Support/VoiceInputMimo/clipboard-archive.txt for recovery
final class TextInjector {
    private var skipIMESwitch: Bool { UserDefaults.standard.bool(forKey: "skipIMESwitch") }
    private var skipClipboardRestore: Bool {
        UserDefaults.standard.object(forKey: "skipClipboardRestore") as? Bool ?? true
    }
    private var markPasteboardTransient: Bool {
        UserDefaults.standard.object(forKey: "markPasteboardTransient") as? Bool ?? true
    }

    func inject(_ text: String) {
        guard !text.isEmpty else { return }

        let pasteboard = NSPasteboard.general

        // Snapshot current clipboard. Always archive (recovery), but only keep
        // in-memory copy for restore if user opted in.
        let savedText = pasteboard.string(forType: .string)
        ClipboardArchive.shared.save(savedText)
        let restoreLater = !skipClipboardRestore ? savedText : nil

        // Write transcription to clipboard. Mark as transient/sensitive so:
        //   - clipboard managers (Paste/Maccy/Pastebot) skip recording it
        //   - macOS may skip Universal Clipboard sync (best-effort)
        pasteboard.clearContents()
        if markPasteboardTransient {
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
            item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
            item.setString("", forType: NSPasteboard.PasteboardType("com.apple.is-sensitive"))
            pasteboard.writeObjects([item])
        } else {
            pasteboard.setString(text, forType: .string)
        }

        // IME switch is the #1 cause of UI freeze (TISSelectInputSource +
        // 50ms blocking sleep on main thread). User can opt out if their
        // target app (Claude Code WebUI, iTerm) is already in ASCII mode.
        var needSwitch = false
        var originalSource: TISInputSource? = nil
        if !skipIMESwitch {
            let current = TISCopyCurrentKeyboardInputSource().takeRetainedValue()
            originalSource = current
            needSwitch = !isASCIICapable(current)

            if needSwitch {
                if let asciiSource = findASCIICapableSource() {
                    TISSelectInputSource(asciiSource)
                    usleep(50_000)
                }
            }
        }

        // Simulate Cmd+V
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKeyCode: CGKeyCode = 0x09

        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cgAnnotatedSessionEventTap)
        keyUp?.post(tap: .cgAnnotatedSessionEventTap)

        // Restore IME after paste (only if we switched)
        if needSwitch, let original = originalSource {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                TISSelectInputSource(original)
            }
        }

        // Restore previous clipboard (opt-in only — default is to leave the
        // refined text in clipboard so a 2nd Cmd+V works without freeze).
        if let saved = restoreLater {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                pasteboard.clearContents()
                pasteboard.setString(saved, forType: .string)
            }
        }
    }

    // MARK: - Input Source Helpers

    private func isASCIICapable(_ source: TISInputSource) -> Bool {
        guard let ptr = TISGetInputSourceProperty(source, kTISPropertyInputSourceIsASCIICapable) else {
            return false
        }
        let value = Unmanaged<CFBoolean>.fromOpaque(ptr).takeUnretainedValue()
        return CFBooleanGetValue(value)
    }

    private func findASCIICapableSource() -> TISInputSource? {
        let criteria = [kTISPropertyInputSourceIsASCIICapable: true, kTISPropertyInputSourceIsEnabled: true] as CFDictionary
        guard let sourceList = TISCreateInputSourceList(criteria, false)?.takeRetainedValue() as? [TISInputSource] else {
            return nil
        }
        for source in sourceList {
            if let idPtr = TISGetInputSourceProperty(source, kTISPropertyInputSourceID) {
                let id = Unmanaged<CFString>.fromOpaque(idPtr).takeUnretainedValue() as String
                if id == "com.apple.keylayout.ABC" || id == "com.apple.keylayout.US" {
                    return source
                }
            }
        }
        return sourceList.first
    }
}
